<?php

namespace AppBundle\Repository;
use \Doctrine\ORM\EntityRepository;
//use AppBundle\Entity\Participante;
/**
 * ParticipanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipanteRepository extends EntityRepository
{
	public function findBySinSorteo1()
	{
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.idSorteo IS NULL');

        $idParticipantes = $qb->getQuery()->getArrayResult();
       
        return $idParticipantes;
	}

	public function findBySinSorteo()
	{
       return $this->getEntityManager()
       ->createQuery('SELECT p FROM AppBundle:Participante p WHERE ( p.idSorteo IS NULL)')
       ->getResult();
	}

  public function findByParticipantesSorteo($id)
  {
       return $this->getEntityManager()
       ->createQuery('SELECT p FROM AppBundle:Participante p WHERE ( p.idSorteo = ?1)')
       ->setParameter(1,$id)
       ->getResult();
  }

    public function findByParticipantesSorteoMaxId($id)
  {
       return $this->getEntityManager()
       ->createQuery('SELECT p FROM AppBundle:Participante p WHERE ( p.idSorteo = ?1) ORDER BY p.id DESC')
       ->setMaxResults(1)
       ->setParameter(1,$id)
       ->getOneOrNullResult();
  }

  public function findByParticipantesSorteoModernos($id,$limit)
  {
       return $this->getEntityManager()
       ->createQuery('SELECT p FROM AppBundle:Participante p WHERE ( p.idSorteo = ?1) ORDER BY p.id DESC')
       ->setParameter(1,$id)
       ->setMaxResults($limit)
       ->getResult();
  }
}
