<?php

namespace AppBundle\Repository;

/**
 * SorteoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SorteoRepository extends \Doctrine\ORM\EntityRepository
{
}
