AppBundle\Entity\Participante:
    type: entity
    table: participante
    indexes:
        sorteo:
            columns:
                - id_sorteo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        correo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        asignado:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        idSorteo:
            targetEntity: Sorteo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_sorteo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
